package Clases;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Josué Marín Montaño
 */
public class Principal extends javax.swing.JFrame{
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Icono1.png"));
        this.setIconImage(iconoPropio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btoProcesos = new javax.swing.JButton();
        btoArchivos = new javax.swing.JButton();
        btoSalir = new javax.swing.JButton();
        btoInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final de Sistemas Operativos");
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        btoProcesos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btoProcesos.setText("Administración memoria");
        btoProcesos.setMaximumSize(new java.awt.Dimension(170, 25));
        btoProcesos.setMinimumSize(new java.awt.Dimension(170, 25));
        btoProcesos.setPreferredSize(new java.awt.Dimension(170, 25));
        btoProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoProcesosActionPerformed(evt);
            }
        });
        getContentPane().add(btoProcesos);
        btoProcesos.setBounds(150, 180, 200, 25);

        btoArchivos.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btoArchivos.setText("Gestor de archivos");
        btoArchivos.setMaximumSize(new java.awt.Dimension(170, 25));
        btoArchivos.setMinimumSize(new java.awt.Dimension(170, 25));
        btoArchivos.setPreferredSize(new java.awt.Dimension(170, 25));
        btoArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoArchivosActionPerformed(evt);
            }
        });
        getContentPane().add(btoArchivos);
        btoArchivos.setBounds(150, 270, 200, 25);

        btoSalir.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btoSalir.setText("Salir");
        btoSalir.setMaximumSize(new java.awt.Dimension(170, 25));
        btoSalir.setMinimumSize(new java.awt.Dimension(170, 25));
        btoSalir.setPreferredSize(new java.awt.Dimension(170, 25));
        btoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btoSalir);
        btoSalir.setBounds(150, 360, 200, 25);

        btoInfo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btoInfo.setText("Información");
        btoInfo.setMaximumSize(new java.awt.Dimension(115, 25));
        btoInfo.setMinimumSize(new java.awt.Dimension(115, 25));
        btoInfo.setPreferredSize(new java.awt.Dimension(115, 25));
        btoInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btoInfo);
        btoInfo.setBounds(350, 420, 124, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 500);
        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btoProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoProcesosActionPerformed
        Procesos procesos = new Procesos(); //Instancia del archivo de los procesos
        procesos.setVisible(true); //Se muestra la ventana de procesos
        this.dispose(); //Se cierra la ventana principal
        
    }//GEN-LAST:event_btoProcesosActionPerformed

    private void btoArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoArchivosActionPerformed
        Archivos archivos = new Archivos(); //Instancia del archivo de los procesos
        archivos.setVisible(true); //Se muestra la ventana de procesos
        this.dispose(); //Se cierra la ventana principal
    }//GEN-LAST:event_btoArchivosActionPerformed

    private void btoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoSalirActionPerformed
        this.dispose(); //Se cierra el menú principal
    }//GEN-LAST:event_btoSalirActionPerformed

    private void btoInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoInfoActionPerformed
        // Crear un mensaje con la información del proyecto
        String mensaje = "<html><h2>Proyecto Final de Sistemas Operativos</h2>" +
                        "<p><strong>Hecho por:</strong></p>" +
                        "<ul>" +
                        "<li>Marín Montaño Josué</li>" +
                        "<li>Hernández Padilla Hugo</li>" +
                        "<li>Rufino López María Elena</li>" +
                        "<li>Ruiz Bastián Oscar</li>" +
                        "</ul>";
        
        JOptionPane.showMessageDialog(null, mensaje, "Información del Proyecto", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btoInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btoArchivos;
    private javax.swing.JButton btoInfo;
    private javax.swing.JButton btoProcesos;
    private javax.swing.JButton btoSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
